# Generated by Django 5.2.14 on 2026-05-25 13:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('event', models.CharField(choices=[('booking_confirmed_user', 'Prenotazione confermata (Utente)'), ('booking_confirmed_specialist', 'Nuova prenotazione (Specialist)'), ('booking_cancelled_user', 'Prenotazione cancellata (Utente)'), ('booking_cancelled_specialist', 'Prenotazione cancellata (Specialist)'), ('booking_status_change_user', 'Aggiornamento prenotazione (Utente)'), ('booking_reminder_user', 'Promemoria prenotazione (Utente)'), ('specialist_request_submitted', 'Nuova richiesta specialist (Admin)'), ('specialist_request_accepted', 'Richiesta specialist approvata'), ('specialist_request_rejected', 'Richiesta specialist rifiutata'), ('specialist_welcome', 'Benvenuto specialist'), ('gift_card_received', 'Gift card ricevuta'), ('payment_refund_issued', 'Rimborso / credito emesso'), ('password_reset', 'Reset password'), ('user_welcome', 'Benvenuto'), ('email_verification', 'Email Verification'), ('new_message_received', 'Nuovo messaggio ricevuto')], max_length=60, unique=True, verbose_name='Evento')),
                ('email_enabled', models.BooleanField(default=True, verbose_name='Email abilitata')),
                ('push_enabled', models.BooleanField(default=False, verbose_name='Push abilitata')),
            ],
            options={
                'verbose_name': 'Configurazione notifica',
                'verbose_name_plural': 'Configurazioni notifiche',
                'ordering': ['event'],
            },
        ),
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('event', models.CharField(choices=[('booking_confirmed_user', 'Prenotazione confermata (Utente)'), ('booking_confirmed_specialist', 'Nuova prenotazione (Specialist)'), ('booking_cancelled_user', 'Prenotazione cancellata (Utente)'), ('booking_cancelled_specialist', 'Prenotazione cancellata (Specialist)'), ('booking_status_change_user', 'Aggiornamento prenotazione (Utente)'), ('booking_reminder_user', 'Promemoria prenotazione (Utente)'), ('specialist_request_submitted', 'Nuova richiesta specialist (Admin)'), ('specialist_request_accepted', 'Richiesta specialist approvata'), ('specialist_request_rejected', 'Richiesta specialist rifiutata'), ('specialist_welcome', 'Benvenuto specialist'), ('gift_card_received', 'Gift card ricevuta'), ('payment_refund_issued', 'Rimborso / credito emesso'), ('password_reset', 'Reset password'), ('user_welcome', 'Benvenuto'), ('email_verification', 'Email Verification'), ('new_message_received', 'Nuovo messaggio ricevuto')], db_index=True, max_length=60, verbose_name='Evento')),
                ('channel', models.CharField(choices=[('email', 'Email'), ('push', 'Push Notification')], max_length=20, verbose_name='Canale')),
                ('recipient_email', models.EmailField(blank=True, max_length=254, verbose_name='Email destinatario')),
                ('status', models.CharField(choices=[('sent', 'Inviato'), ('failed', 'Fallito'), ('skipped', 'Saltato')], db_index=True, default='sent', max_length=20, verbose_name='Stato')),
                ('error', models.TextField(blank=True, verbose_name='Errore')),
                ('context_snapshot', models.JSONField(default=dict, verbose_name='Snapshot contesto')),
                ('object_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
                ('recipient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notification_logs', to=settings.AUTH_USER_MODEL, verbose_name='Destinatario')),
            ],
            options={
                'verbose_name': 'Log notifica',
                'verbose_name_plural': 'Log notifiche',
                'ordering': ['-created_date'],
                'indexes': [models.Index(fields=['event', 'status'], name='notificatio_event_665ecd_idx'), models.Index(fields=['recipient', '-created_date'], name='notificatio_recipie_e78475_idx')],
            },
        ),
    ]
